# Generated by Django 4.0.5 on 2022-06-24 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(blank=True, choices=[('Normal Post', 'Normal Post'), ('Photo Uploaded Post', 'Photo Uploaded Post')], default='Normal Post', max_length=120, null=True),
        ),
    ]
