# Generated by Django 4.0.5 on 2022-06-24 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_delete_activateuser'),
        ('post', '0002_post_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user_profile_pic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.accountprofilepics'),
        ),
        migrations.AddField(
            model_name='like',
            name='user_profile_pic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.accountprofilepics'),
        ),
        migrations.AddField(
            model_name='post',
            name='user_profile_pic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.accountprofilepics'),
        ),
    ]
