# Generated by Django 4.0.5 on 2022-06-24 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_comment_user_profile_pic_like_user_profile_pic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user_profile_pic',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user_profile_pic',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user_profile_pic',
        ),
    ]
