# Generated by Django 4.0.5 on 2022-06-24 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_remove_comment_user_profile_pic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_type',
        ),
    ]
