# Generated by Django 4.0.5 on 2022-06-30 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0003_rename_friend_requet_senders_friendrequest_friend_request_senders'),
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='friend',
        ),
        migrations.AddField(
            model_name='notification',
            name='friend_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_friend_request', to='friend.friendrequest'),
        ),
    ]
