# Generated by Django 4.0.5 on 2022-07-07 11:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='chatcounter',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='chatmessageseen',
            options={'ordering': ('-created_at',)},
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('chat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_message_chat', to='chat.chat')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
