# Generated by Django 4.0.5 on 2022-06-22 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_account_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivateUser',
        ),
    ]
