# Generated by Django 4.0.5 on 2022-06-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_remove_comment_user_profile_pic_and_more'),
        ('authentication', '0004_delete_activateuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='all_profile_pics',
            field=models.ManyToManyField(blank=True, to='authentication.userprofilepic'),
        ),
        migrations.AddField(
            model_name='account',
            name='current_profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile'),
        ),
        migrations.DeleteModel(
            name='AccountProfilePics',
        ),
    ]
