# Generated by Django 4.0.5 on 2022-06-25 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_account_all_profile_pics_account_current_profile_pic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='studying_at',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='working_at',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
