# Generated by Django 4.0.5 on 2022-06-25 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_account_studying_at_account_working_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='job_position',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
