# Generated by Django 4.0.5 on 2022-06-25 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_account_job_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='description',
        ),
    ]
