# Generated by Django 4.0.5 on 2022-06-29 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0002_friendrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendrequest',
            old_name='friend_requet_senders',
            new_name='friend_request_senders',
        ),
    ]
